# Generates a C++ header with the Quark stdlib embedded as raw string literals.
#
# Usage:
#   cmake -DQUARK_STD_DIR=<abs std dir> -DOUTPUT_HEADER=<abs header> -P embed_std.cmake

# Raw-string delimiter must be at most 16 characters (C++ standard limit).
set(STD_EMBED_DELIM "QKSTD6E8D2A4B9C1")

# Some CMake versions pass -D values through a shell that keeps the quotes.
# Strip any surrounding quotes so they cannot corrupt paths or create stray
# directories (e.g. a directory literally named '"').
string(REPLACE "\"" "" QUARK_STD_DIR "${QUARK_STD_DIR}")
string(REPLACE "\"" "" OUTPUT_HEADER "${OUTPUT_HEADER}")

file(GLOB_RECURSE std_qk_files "${QUARK_STD_DIR}/*.qk")
list(SORT std_qk_files)

set(content "// Generated by scripts/embed_std.cmake. Do not edit.\n")
string(APPEND content "#pragma once\n")
string(APPEND content "#include <string>\n")
string(APPEND content "#include <utility>\n")
string(APPEND content "#include <vector>\n")
string(APPEND content "\n")
string(APPEND content "namespace quark::embedded_std {\n")
string(APPEND content "inline const std::vector<std::pair<std::string, std::string>>& std_modules() {\n")
string(APPEND content "    static const std::vector<std::pair<std::string, std::string>> kModules = {\n")

foreach(file IN LISTS std_qk_files)
  file(RELATIVE_PATH rel "${QUARK_STD_DIR}" "${file}")
  string(REPLACE "\\" "/" rel "${rel}")
  set(rel "std/${rel}")
  file(READ "${file}" src)

  # A file containing the raw-string terminator cannot be embedded verbatim.
  string(FIND "${src}" ")${STD_EMBED_DELIM}\"" bad_pos)
  if(NOT bad_pos EQUAL -1)
    message(FATAL_ERROR
            "Cannot embed ${rel}: it contains the raw string delimiter '${STD_EMBED_DELIM}'")
  endif()

  string(APPEND content "        {\"${rel}\", R\"${STD_EMBED_DELIM}(${src})${STD_EMBED_DELIM}\"},\n")
endforeach()

string(APPEND content "    };\n")
string(APPEND content "    return kModules;\n")
string(APPEND content "}\n")
string(APPEND content "} // namespace quark::embedded_std\n")

get_filename_component(out_dir "${OUTPUT_HEADER}" DIRECTORY)
file(MAKE_DIRECTORY "${out_dir}")
file(WRITE "${OUTPUT_HEADER}" "${content}")

message(STATUS "Embedded stdlib: ${std_qk_files} file(s) -> ${OUTPUT_HEADER}")
